re PR c/14171 (Bootstrap (--enable-intermodule) dies with reg-stack.c:235: error: 'nan' redeclared as different kind of symbol)
2004-05-19  Andrew Pinski  <pinskia@physics.uc.edu>

        PR c/14171
        * reg-stack.c (nan): Rename to ...
        (not_a_num): Here.
        (reg_to_stack): Rename nan to not_a_num.
        (subst_stack_regs_pat): Likewise.
        (convert_regs_entry): Likewise.
        (convert_regs_1): Likewise.

From-SVN: r82040