rs6000: Fix pr18096-1.c test
For the big stack frame in the test GCC used to say

pr18096-1.c:7:6: error: total size of local objects too large

but now it says

pr18096-1.c:7:6: error: total size of local objects 2147483647 exceeds maximum 2147483392

Let's just allow both in the test.


gcc/testsuite/
	* gcc.target/powerpc/pr18096-1.c: Allow an error message that says
	"exceeds" instead of just one that talks about "too large".

From-SVN: r269770