re PR middle-end/27736 (unwind-dw2-fde.c:833: fatal error: internal consistency failure)
	PR rtl-optimization/27736
	* combine.c (replaced_rhs_value): New variable.
	(combine_instructions): Set it.
	(distribute_notes): When distributing a note in replaced_rhs_insn,
	check whether the value was used in replaced_rhs_value.

From-SVN: r114019