re PR libfortran/63471 (unix.c:1906:10: error: implicit declaration of function 'ttyname_r')
	PR libfortran/63471
        * config/pa/pa-hpux11.h (TARGET_OS_CPP_BUILTINS): Define _REENTRANT
        when _HPUX_SOURCE is defined.

From-SVN: r216152