re PR other/64370 (sreal.c:125:23: error: 'exp2' was not declared in this scope)
	PR other/64370
	* sreal.c (sreal::to_double): Use ldexp instead of scalbnl.

From-SVN: r219489