re PR target/55042 (sh.c:11586:1: error: ‘bool sh1_builtin_p()’ defined but not used)
	PR target/55042
	* config/sh/sh.c (sh1_builtin_p): Comment out unused function.

From-SVN: r192877