re PR middle-end/47610 (cp-demangle.c:1970:1: error: cplus_demangle_builtin_types causes a section type conflict)
	PR middle-end/47610
	* varasm.c (default_section_type_flags): If decl is NULL,
	and name is .data.rel.ro or .data.rel.ro.local, set SECTION_RELRO
	bit.

	* gcc.dg/pr47610.c: New test.

From-SVN: r169855