re PR target/56444 (mn10300.c:3228:16: error: unused variable ‘loops’)
2013-02-26  Richard Biener  <rguenther@suse.de>

	PR target/56444
	* config/mn10300/mn10300.c (mn10300_scan_for_setlb_lcc): Remove
	unused variable loops.

From-SVN: r196280