[testsuite] Fix TCL syntax error in 'scan-dump-dem-not'
    ERROR: [...]: error executing dg-final: missing close-bracket

Bug introduced in commit 2ef1bce664881cd59dac7db6c3f3b5709d858bfe (r188996),
long ago.

	gcc/testsuite/
	* lib/scandump.exp (scan-dump-dem-not): Fix TCL syntax error.