re PR target/55034 (avr.c:2877:7: error: variable ‘regno_dest’ set but not used)
	PR target/55034
	* config/avr/avr.c (avr_out_lpm): Remove unused regno_dest.

From-SVN: r192878